# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'v*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    touch $(Agent.TempDirectory)/.npmrc
    echo '##vso[task.setvariable variable=NPM_CONFIG_USERCONFIG]$(Agent.TempDirectory)/.npmrc'
  displayName: 'create user .npmrc file'

- task: npmAuthenticate@0
  inputs:
    workingFile: '$(Agent.TempDirectory)/.npmrc'
    customEndpoint: 'npmjs'

- script: |
    npm config ls
    npm shrinkwrap
    npm publish
  displayName: 'npm publish'
  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
